# Generated by Django 5.0.4 on 2024-05-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('urgent', models.CharField(choices=[('Low', 'Низкая'), ('Medium', 'Средняя'), ('High', 'Высокая')], max_length=6)),
                ('status', models.CharField(choices=[('New', 'Новая'), ('In process', 'В процессе'), ('Done', 'Завершена')], default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
